name: Firmware Release

on:
  push:
    paths:
      - .github/workflows/**
      - src/software/firmware/**
  pull_request:
    paths:
      - .github/workflows/**
      - src/software/firmware/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0

      - name: Install STM libs
        run: |
          arduino-cli config init --additional-urls https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
          arduino-cli config dump
          arduino-cli core update-index
          arduino-cli core install STM32:stm32
          arduino-cli lib install LiquidCrystal
          arduino-cli lib install "Analog Buttons"
          arduino-cli lib install OneButton
          sed -i '/recipe.output.tmp_file={build.project_name}.hex/d' "$HOME/.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt"
          sed -i '/recipe.output.save_file={build.project_name}.{build.variant}.hex/d' "$HOME/.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt"

      - name: Get the version
        id: version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Set VERSION variable
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && steps.version.outputs.version != ''
        run: |
          sed -Ei "s/#define VERSION \".+\"/#define VERSION \"${{ steps.version.outputs.version }}\"/" src/software/firmware/includes/parameters.h

      - name: Build production HW2-FAULHABER
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/respirator.cpp --output src/software/firmware/output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-production.bin "dist/respirator-production-HW2-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build qualification HW2-FAULHABER
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_QUALIFICATION/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/qualification.cpp --output src/software/firmware/output/respirator-qualification
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-qualification.bin "dist/respirator-qualification-HW2-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build integration test HW2-FAULHABER
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_INTEGRATION_TEST/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_FAULHABER/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_FAULHABER/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/qualification.cpp --output src/software/firmware/output/respirator-integration-test
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-integration-test.bin "dist/respirator-integration-test-HW2-FAULHABER-$VERSION-$GITHUB_SHA.bin"

      - name: Build production HW2
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/respirator.cpp --output src/software/firmware/output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-production.bin "dist/respirator-production-HW2-$VERSION-$GITHUB_SHA.bin"

      - name: Build qualification HW2
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_QUALIFICATION/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/qualification.cpp --output src/software/firmware/output/respirator-qualification
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-qualification.bin "dist/respirator-qualification-HW2-$VERSION-$GITHUB_SHA.bin"

      - name: Build integration test HW2
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 2/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_INTEGRATION_TEST/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/qualification.cpp --output src/software/firmware/output/respirator-integration-test
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-integration-test.bin "dist/respirator-integration-test-HW2-$VERSION-$GITHUB_SHA.bin"

      - name: Build production HW1
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 1/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_PROD/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/respirator.cpp --output src/software/firmware/output/respirator-production
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-production.bin "dist/respirator-production-HW1-$VERSION-$GITHUB_SHA.bin"

      - name: Build qualification HW1
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 1/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_QUALIFICATION/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/qualification.cpp --output src/software/firmware/output/respirator-qualification
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-qualification.bin "dist/respirator-qualification-HW1-$VERSION-$GITHUB_SHA.bin"

      - name: Build integration test HW1
        run: |
          sed -Ei 's/#define HARDWARE_VERSION [0-9]+/#define HARDWARE_VERSION 1/' src/software/firmware/includes/config.h
          sed -Ei 's/#define MODE .+/#define MODE MODE_INTEGRATION_TEST/' src/software/firmware/includes/config.h
          sed -Ei 's/#define PNEUMATIC_HARDWARE_VERSION .+/#define PNEUMATIC_HARDWARE_VERSION PHW_CHU/' src/software/firmware/includes/config.h
          sed -Ei 's/#define VALVE_TYPE .+/#define VALVE_TYPE VT_SERVO_V1/' src/software/firmware/includes/config.h
          arduino-cli compile --fqbn STM32:stm32:Nucleo_64:opt=o3std,pnum=NUCLEO_F411RE --verbose src/software/firmware/srcs/qualification.cpp --output src/software/firmware/output/respirator-integration-test
          mkdir -p dist/
          VERSION=$(sed -En 's/#define VERSION[ ]+["](.+)["]/\1/p' src/software/firmware/includes/parameters.h)
          cp src/software/firmware/output/respirator-integration-test.bin "dist/respirator-integration-test-HW1-$VERSION-$GITHUB_SHA.bin"

      - name: Archive binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: dist/

      - name: Release dev binaries
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          files: |
            dist/*.bin
          body: |
            Auto-release (${{ github.sha }})
            ⚠️ FOR TEST PURPOSE ONLY - DO NOT USE IN PRODUCTION
          tag_name: auto-${{ github.run_id }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release stable binaries
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && steps.version.outputs.version != ''
        with:
          files: |
            dist/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
